# Generated by Django 4.2 on 2023-04-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('long', 'Long'), ('short', 'Short')], max_length=5)),
                ('entry', models.FloatField()),
                ('take_profit', models.FloatField(blank=True)),
                ('stop_loss', models.FloatField(blank=True)),
                ('notes', models.TextField(max_length=3000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='trades/')),
                ('risk_reward', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('entry_time', models.DateTimeField(blank=True, null=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
