# Generated by Django 4.2 on 2023-04-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0002_alter_trade_stop_loss_alter_trade_take_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='notes',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
    ]
